
# version: '3'
# services:
#   jenkins:
#     image: alperensayar/jenkinswithdocker
#     container_name: c_jenkins
#     ports:
#       - 8080:8080
#       - 50000:50000
#     privileged: true
#     volumes:
#       - /Users/alperensayar/Desktop/CICD/jenkins_data:/var/jenkins_home
#       - /var/run/docker.sock:/var/run/docker.sock

version: '3.1'

services:
  backend:
    image: backend_file
    container_name: c_backend
    ports:
      - 8005:8000
    environment:
      - PYTHONUNBUFFERED=1
    