
version: '3.1'

services:
  s_jenkins:
    container_name: c_jenkins
    image: alperensayar/jenkinswithdocker
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /Users/alperensayar/Desktop/CICD/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  

